config/routes.rb
Judgy::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users
  resources :projects
  resources :comments
  resources :lists
  resources :reports
  root "lists#new"
  get "pages/beta"
  get "pages/panel"
  get "pages/access"

end

app/models/report.rb
class Report < ActiveRecord::Base
	has_attached_file :image, styles: { thumb: '120x120', large: '700x450', twitter: '1000x500', facebook: '1000x500' }, 
    :convert_options => {:facebook => "-gravity center -extent 1000x500^"}
  
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 2.megabytes }
  validates :overall_grade, presence: true
  validates :pain_grade, presence: true
  validates :fix_grade, presence: true
  belongs_to :user
  belongs_to :project
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :admin_user

  def index
    @reports = Report.all
  end

	def new
		@project = Project.find(params[:project_id])
    @header = "JudgeReport for #{@project.project_name}"
	  @report = Report.new
	  @grades = ["A","B","C","D","F"]
	end

  def create
    @report = Report.new(report_params)
    @report.user_id = current_user.id

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'JudgeReport created successfully.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
		@report = Report.find(params[:id])
	end

	def edit
    @header = "Edit Project"
    @report = Report.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  def update
    @report = Report.find(params[:id])
    @report.user_id = current_user.id
    
    if @report.update_attributes(report_params)
      flash[:success] = "JudgeReport updated"
      redirect_to @report
    else
      render 'edit'
    end
  end


	private

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:image, :project_id, :overall_grade, :fix_grade, :pain_grade)
    end

    def admin_user
      unless current_user.try(:admin?)
        redirect_to(root_url)
        flash[:alert] = 'You must be an admin to access that page.'
      end
    end 
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/edit.html.erb
<div class="border-form-div">
  <h2><%= @header %></h2>
	  <%= simple_form_for(@report, html: {class: "form-horizontal"}) do |f| %>
	  	<%= f.error_notification %>
	  	<%= f.input :project_id, :input_html => { :value => @project.id}, label: @project.project_name %>
	  	<%= f.full_error :image_file_size, class: 'alert alert-error' %>
	  	<%= f.full_error :image_content_type, class: 'alert alert-error' %>
			
			<%= f.input :image, label: 'Upload JudgeReport Image' %>
	    <%= f.input :overall_grade, :collection => @grades %>
	    <%= f.input :pain_grade, :collection => @grades %>
	    <%= f.input :fix_grade, :collection => @grades %>

			<%= f.submit "Submit JudgeReport", class: "btn-action-bottom" %>
		<% end %>
</div>

app/views/reports/index.html.erb
<div class="control_basic">  
  <h1>Listing reports</h1>

  <table class="index_table">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= image_tag(report.project.image(:thumb)) %></td>
          <td><%= image_tag(report.image(:thumb)) %></td>
          <td><%= report.id %></td>
          <td><%= report.project.project_name %></td>
          <td><%= report.project.user.email %></td>
          <td><%= link_to 'Show', report %></td>
          <td><%= link_to 'Edit', edit_report_path(report, :project_id => report.project_id) %></td>
          <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/reports/new.html.erb
<div class="border-form-div">
  <h2><%= @header %></h2>
	  <%= simple_form_for(@report, html: {class: "form-horizontal"}) do |f| %>
	  	<%= f.error_notification %>
	  	<%= f.input :project_id, :input_html => { :value => @project.id}, label: @project.project_name %>
	  	<%= f.full_error :image_file_size, class: 'alert alert-error' %>
	  	<%= f.full_error :image_content_type, class: 'alert alert-error' %>
			
			<%= f.input :image, label: 'Upload JudgeReport Image' %>
	    <%= f.input :overall_grade, :collection => @grades %>
	    <%= f.input :pain_grade, :collection => @grades %>
	    <%= f.input :fix_grade, :collection => @grades %>

			<%= f.submit "Submit JudgeReport", class: "btn-action-bottom" %>
		<% end %>
</div>

app/views/reports/show.html.erb
<div class="show_wrapper">
	<h1>JudgeReport for <%= @report.project.project_name %></h1>

	<div class="main_show" >
		<span class="helper"></span><%= image_tag(@report.image(:large)) %> 
	</div>

	<div class="side_show">
		<h2>
				<%= @report.project.project_name %></br>
				<%= @report.project.tagline %></br>
				<% if @report.user %>
					<%= @report.user.email %></br>
				<% else %>
					<p>User ID Not Fixed</p>
				<% end %>

				<%= image_tag(@report.project.image(:thumb))  %></br>
				<%= link_to "Edit Report", edit_report_path(@report, :project_id => @report.project_id), class: "btn btn-default btn-large" %>
		</h2>
	</div>
</div>