config/routes.rb
Judgy::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users
  resources :projects
  resources :comments
  resources :lists
  resources :reports
  root "lists#new"
  get "pages/beta"
  get "pages/panel"
  get "pages/access"

end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
     <%= js add_gritter(msg, class_name: "gritter-light") %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
	<div class="foot_center">
	<p>&copy; 2014 JURY, Inc. by <%= link_to("Chris Finlayson", "https://twitter.com/chrisjfin") %> </p>

		<div class="footer_social">
		<%= link_to image_tag("twitter-32.png"), "http://twitter.com/thejuryco", :target => "_blank" %>
		</div>
	</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand"><%= link_to "JURY", root_path %></div>
        <ul class="nav navbar-nav navbar-right"> 
          
        	<% if user_signed_in? %>
            <li><%= link_to "Submit a Pitch", new_project_path %></li>
        		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        	<% elsif cookies[:email] %>
            <li><%= link_to "Submit a Pitch", new_project_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
          <% else %>
            <li><%= link_to "Join the Beta", new_user_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
          <!-- <li><%= link_to "Blog", "#" %></li> -->
        </ul>
    </div>
  </div>
</header>

app/views/layouts/_meta_social.html.erb
<% if @project %>
	<!-- Meta tages for Facebook sharing -->
	<meta property="og:title" content="<%= yield(:title) %>" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="<%= request.original_url %>" />
	<meta property="og:image" content="<%= image_url @project.image(:facebook) %>" />
	<meta property="og:description" content="What do you think of this startup idea? Weigh in at the JURY." />

	<!-- Meta tages for Twitter sharing -->
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="@theJURYco">
	<meta name="twitter:title" content="<%= yield(:title) %>">
	<meta name="twitter:description" content="What do you think of this startup idea? Weigh in @theJURYco">
	<meta name="twitter:creator" content="<%= @project.twitter %>">
	<meta name="twitter:image:src" content="<%= image_url @project.image(:twitter) %>">
	<meta name="twitter:domain" content="<%= request.original_url %>">

<% end %>

app/views/layouts/application.html.erb
<% provide(:title, @title ||= 'JURY - Build Better Startups') %>
<!DOCTYPE html>
<html>
<head>
	
	<%= render 'layouts/meta_social' %>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'juryfav.ico' %>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55214550-1', 'auto');
  ga('send', 'pageview');

	</script>


</head>
<body>  
	<div class="wrapper">
		<%= render 'layouts/header' %>	
		<%= render 'layouts/flash' %>

		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>